name: CI/CD Pipeline - MS Cobros

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo fuente
      uses: actions/checkout@v3

    - name: Validar estructura del proyecto
      run: |
        echo "Validando archivos del microservicio..."
        ls -la

    - name: Simular Pruebas Unitarias
      run: echo "Pruebas unitarias ejecutadas exitosamente."

    - name: Simular Build de Docker
      run: echo "Imagen Docker construida exitosamente."
